In [1]:
import numpy as np

In [2]:
# Escribamos nuevamente nuestros elementos y veamos como funciona el broadcasting

escalar = 5.6789
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [3]:
# La libreria NumPy nos permite realizar operaciones con arrays de distintas dimensiones. La manera de hacerlo es
# extendiendo el elemento de menor dimension hasta igualar el mas grande. Las reglas generales para hacer
# broadcasting son las dimensiones coinciden o una de ellas es igual a 1
# para conocer mas del funcionamiento https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html
print(vector.shape)
print(matriz.shape)

(3,)
(3, 2)


In [4]:
# Matematicamente hablando la operacion no estaria definida, pero con Python podemos ver que ocurre si las
# condiciones correctas estan dadas, esto es que la dimension del menor pueda ser extendido
A = vector + matriz
print(A.shape)
print(A)

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [5]:
B = matriz.T + vector

print("Matriz (transpuesta) y vector con el que vamos a operar")
print(matriz.T)
print(vector)

print("Dimensiones de los arrays")
print(B.shape)
print(vector.shape)

print("Matriz resultante de la suma")
print(B)

Matriz (transpuesta) y vector con el que vamos a operar
[[1 3 5]
 [2 4 6]]
[3 4 5]
Dimensiones de los arrays
(2, 3)
(3,)
Matriz resultante de la suma
[[ 4  7 10]
 [ 5  8 11]]


In [18]:
# Tambien hicimos broadcasting cuando sumamos un escalar y una matriz
C = matriz + 42
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [20]:
D = matriz + [[42],[42],[42]]
print(D)

[[43 44]
 [45 46]
 [47 48]]


# Ejercicio

In [7]:
# Hacer la suma de un vector de dimension 5 con una matriz de dimension 5x5
v = np.array([[1],[2],[3],[4],[5]])
E = np.array([[2,3,5,7,9],[2,3,5,7,9],[2,3,5,7,9],[2,3,5,7,9],[2,3,5,7,9]])
print("Dimensiones del vector: ", v.shape)
print("Dimensiones de la matriz: ", E.shape)
print("Suma del vector y la matriz")
print(E+v)

Dimensiones del vector:  (5, 1)
Dimensiones de la matriz:  (5, 5)
Suma del vector y la matriz
[[ 3  4  6  8 10]
 [ 4  5  7  9 11]
 [ 5  6  8 10 12]
 [ 6  7  9 11 13]
 [ 7  8 10 12 14]]


In [ ]:
# The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. 
# Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have 
# compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C
# instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm
# implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of
# memory that slows computation.